apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triliovault-datamover-api
  namespace: trilio-openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-triliovault-datamover-api
subjects:
  - kind: ServiceAccount
    name: triliovault-datamover-api
    namespace: trilio-openstack
    
---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triliovault-datamover-api-anyuid
  namespace: trilio-openstack
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: triliovault-datamover-api
    namespace: trilio-openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triliovault-datamover-api-privileged
  namespace: trilio-openstack
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: triliovault-datamover-api
    namespace: trilio-openstack