apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-triliovault-datamover-api
  namespace: trilio-openstack
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - jobs
      - pods
