apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: triliovault-datamover-public
  namespace: trilio-system
  labels:
    osctlplane-service: triliovault-datamover
spec:
  host: {{ .Values.keystone.datamover_api.public_auth_host }}
  to:
    kind: Service
    name: triliovault-datamover-public
    weight: 100
  port:
    targetPort: triliovault-datamover-public
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None