---
apiVersion: v1
kind: Secret
metadata:
  name: triliovault-datamover-api-etc
type: Opaque
data:
  triliovault-datamover-api.conf: |
    {{ tpl (.Files.Get "conf/_triliovault_datamover_api_conf.tpl") . | b64enc }}
  datamover_api_logging.conf: |
    {{ tpl (.Files.Get "conf/_datamover_api_logging_conf.tpl") . | b64enc }}
  ca-cert.pem: {{ .Values.keystone.common.ca_cert | b64enc }}
  triliovault_datamover_httpd.conf: |
    {{ tpl (.Files.Get "conf/_triliovault_datamover_httpd_conf.tpl") . | b64enc }}
