---

- name: triliovault - Load rbd module
  include_role:
    name: module-load
  vars:
    modules:
      - { name: rbd }
  when:
    - inventory_hostname in groups[triliovault_datamover_group]

- name: triliovault - set nbd module options in modprobe conf
  become: true
  template:
    src: modprobe-nbd.conf.j2
    dest: "/etc/modprobe.d/nbd.conf"
  when:
    - inventory_hostname in groups[triliovault_datamover_group]

- name: triliovault - set module-load conf for nbd module
  become: true
  template:
    src: module-load-nbd.conf.j2
    dest: "/etc/modules-load.d/nbd.conf"
  when:
    - inventory_hostname in groups[triliovault_datamover_group]

- name: triliovault - load nbd module
  become: true
  modprobe:
    name: "nbd"
    params: "nbds_max=128"
    state: "present"
  when:
    - inventory_hostname in groups[triliovault_datamover_group]

- name: Create log directories
  become: true
  file:
    path: "/var/log/kolla/{{ item.key }}"
    state: "directory"
    owner: "{{ item.value.run_user }}"
    group: "{{ item.value.run_group }}"
    mode: "0755"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ triliovault_services }}"

- name: Ensuring config directories exist
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ triliovault_services }}"

- name: Ensuring /var/trilio directory exist
  become: true
  file:
    path: "{{ triliovault_parent_data_directory }}"
    state: "directory"
    owner: "{{ triliovault_datamover_user_id }}"
    group: "{{ triliovault_datamover_group_id }}"
    mode: "0755"
  when: >
        ( inventory_hostname in groups[triliovault_datamover_group] ) or
        ( inventory_hostname in groups[triliovault_wlm_api_group] ) or
        ( inventory_hostname in groups[triliovault_wlm_workloads_group] ) or
        ( inventory_hostname in groups[triliovault_wlm_scheduler_group] ) or
        ( inventory_hostname in groups[triliovault_wlm_cron_group] )

- name: Ensuring "{{ triliovault_parent_data_directory }}/triliovault-mounts"  directory exist
  become: true
  file:
    path: "{{ triliovault_parent_data_directory }}/triliovault-mounts"
    state: "directory"
    owner: "{{ triliovault_datamover_user_id }}"
    group: "{{ triliovault_datamover_group_id }}"
    mode: "0755"
  when: >
        ( inventory_hostname in groups[triliovault_datamover_group] ) or
        ( inventory_hostname in groups[triliovault_wlm_api_group] ) or
        ( inventory_hostname in groups[triliovault_wlm_workloads_group] ) or
        ( inventory_hostname in groups[triliovault_wlm_scheduler_group] ) or
        ( inventory_hostname in groups[triliovault_wlm_cron_group] )

- include_tasks: copy-certs.yml
  when:
    - kolla_copy_ca_into_containers | bool

- import_tasks: get_cloud_details.yml

##json

- name: Copying over config.json files for services
  become: true
  template:
    src: "{{ item.key }}.json.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/config.json"
    mode: "0660"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart {{ item.key }} container"

##config

- name: Copying triliovault wlm conf file
  become: true
  template:
    src: "triliovault-wlm.conf.j2"
    dest: "{{ node_config_directory }}/{{ item }}/{{ item }}.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[item]
  with_items:
    - triliovault-wlm-api
    - triliovault-wlm-cron
    - triliovault-wlm-scheduler
    - triliovault-wlm-workloads
  notify:
    - "Restart {{ item }} container"

- name: Copying triliovault datamover and datamover api conf files
  become: true
  template:
    src: "{{ item }}.conf.j2"
    dest: "{{ node_config_directory }}/{{ item }}/{{ item }}.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[item]
  with_items:
    - triliovault-datamover-api
    - triliovault-datamover
  notify:
    - "Restart {{ item }} container"

- name: Copying triliovault-object-store conf files
  become: true
  template:
    src: "triliovault-object-store.conf.j2"
    dest: "/etc/kolla/triliovault-wlm-api/triliovault-object-store.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_wlm_api_group]
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart triliovault-wlm-api container"

- name: Copying fuse conf files
  become: true
  template:
    src: "fuse.conf.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/fuse.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart {{ item.key }} container"

##logging_conf

- name: Copying triliovault-datamover-api-logging-conf files
  become: true
  template:
    src: "triliovault-datamover-api-logging.conf.j2"
    dest: "/etc/kolla/triliovault-datamover-api/triliovault-datamover-api-logging.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_datamover_api_group]
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart triliovault-datamover-api container"

- name: Copying triliovault-datamover-logging-conf files
  become: true
  template:
    src: "triliovault-datamover-logging.conf.j2"
    dest: "/etc/kolla/triliovault-datamover/triliovault-datamover-logging.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_datamover_group]
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart triliovault-datamover container"

- name: Copying triliovault-object-store-logging-wlm-conf files
  become: true
  template:
    src: "triliovault-object-store-logging.conf.j2"
    dest: "/etc/kolla/triliovault-wlm-api/triliovault-object-store-logging.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_wlm_api_group]
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart triliovault-wlm-api container"

- name: Copy triliovault-wlm-api-logging.conf file
  become: true
  template:
    src: "triliovault-wlm-logging.conf"
    dest: "/etc/kolla/triliovault-wlm-api/triliovault-wlm-logging.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_wlm_api_group]
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart triliovault-wlm-api container"

- name: Copy triliovault-wlm-workloads-logging.conf file
  become: true
  template:
    src: "triliovault-wlm-logging.conf"
    dest: "/etc/kolla/triliovault-wlm-workloads/triliovault-wlm-logging.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_wlm_workloads_group]
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart triliovault-wlm-workloads container"

- name: Copy triliovault-wlm-scheduler-logging.conf file
  become: true
  template:
    src: "triliovault-wlm-logging.conf"
    dest: "/etc/kolla/triliovault-wlm-scheduler/triliovault-wlm-logging.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_wlm_scheduler_group]
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart triliovault-wlm-scheduler container"

- name: Copy triliovault-wlm-cron-logging.conf file
  become: true
  template:
    src: "triliovault-wlm-logging.conf"
    dest: "/etc/kolla/triliovault-wlm-cron/triliovault-wlm-logging.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_wlm_cron_group]
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart triliovault-wlm-cron container"

##api-paste.ini
      
- name: Copy triliovault-wlm api-paste.ini file to api
  become: true
  template:
    src: "api-paste.ini.j2"
    dest: "{{ node_config_directory }}/triliovault-wlm-api/api-paste.ini"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_wlm_api_group]
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart triliovault-wlm-api container"

- name: Copy triliovault-wlm api-paste.ini file to workloads
  become: true
  template:
    src: "api-paste.ini.j2"
    dest: "{{ node_config_directory }}/triliovault-wlm-workloads/api-paste.ini"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_wlm_workloads_group]
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart triliovault-wlm-workloads container"

- name: Copy triliovault-wlm api-paste.ini file to scheudler
  become: true
  template:
    src: "api-paste.ini.j2"
    dest: "{{ node_config_directory }}/triliovault-wlm-scheduler/api-paste.ini"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_wlm_scheduler_group]
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart triliovault-wlm-scheduler container"

- name: Copy triliovault-wlm api-paste.ini file to cron
  become: true
  template:
    src: "api-paste.ini.j2"
    dest: "{{ node_config_directory }}/triliovault-wlm-cron/api-paste.ini"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_wlm_cron_group]
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart triliovault-wlm-cron container"

- include_tasks: ceph_cinder.yml
  when:
    - cinder_backend_ceph | bool
    - inventory_hostname in groups[triliovault_datamover_group]
- name: Copy over triliovault backup target certs - ceph s3 for triliovault-datamover
  copy:
    src: "{{ node_custom_config }}/triliovault/{{ triliovault_s3_ssl_cert_file_name }}"
    dest: "{{ node_config_directory }}/triliovault-datamover/triliovault-s3.pem"
    mode: "0660"
  become: true
  when:
    - triliovault_copy_ceph_s3_ssl_cert | bool
    - inventory_hostname in groups[triliovault_datamover_group]
  notify:
    - Restart triliovault-datamover container
- name: Copy over triliovault backup target certs - ceph s3 for triliovault-wlm-api
  copy:
    src: "{{ node_custom_config }}/triliovault/{{ triliovault_s3_ssl_cert_file_name }}"
    dest: "{{ node_config_directory }}/triliovault-wlm-api/triliovault-s3.pem"
    mode: "0660"
  become: true
  when:
    - triliovault_copy_ceph_s3_ssl_cert | bool
    - inventory_hostname in groups[triliovault_wlm_api_group]
  notify:
    - Restart triliovault-wlm-api container


- name: Copy over triliovault backup target certs - ceph s3 for triliovault-wlm-workloads
  copy:
    src: "{{ node_custom_config }}/triliovault/{{ triliovault_s3_ssl_cert_file_name }}"
    dest: "{{ node_config_directory }}/triliovault-wlm-workloads/triliovault-s3.pem"
    mode: "0660"
  become: true
  when:
    - triliovault_copy_ceph_s3_ssl_cert | bool
    - inventory_hostname in groups[triliovault_wlm_workloads_group]
  notify:
    - Restart triliovault-wlm-workloads container


- name: Copy over triliovault backup target certs - ceph s3 for triliovault-wlm-scheduler
  copy:
    src: "{{ node_custom_config }}/triliovault/{{ triliovault_s3_ssl_cert_file_name }}"
    dest: "{{ node_config_directory }}/triliovault-wlm-scheduler/triliovault-s3.pem"
    mode: "0660"
  become: true
  when:
    - triliovault_copy_ceph_s3_ssl_cert | bool
    - inventory_hostname in groups[triliovault_wlm_scheduler_group]
  notify:
    - Restart triliovault-wlm-scheduler container


- name: Copying over nova.conf for triliovault datamover service
  become: true
  vars:
    service_name: "triliovault-datamover"
  copy:
    src: "{{ node_config_directory }}/nova-compute/nova.conf"
    dest: "{{ node_config_directory }}/triliovault-datamover/nova.conf"
    mode: "0660"
    remote_src: yes
  when:
    - inventory_hostname in groups[triliovault_datamover_group]
    - enable_triliovault | bool
  notify:
    - "Restart triliovault-datamover container"

- include_tasks: check-containers.yml
  when: kolla_action != "config"

