---

- name: Create Cloud Admin Trust
  hosts: triliovault-wlm-api
  become: true
  gather_facts: false
  tasks:
    - name: Create Cloud Admin Trust
      become: true
      docker_container:
        name: wlm_cloud_trust
        image: "{{ triliovault_docker_registry }}/trilio/kolla-{{ kolla_base_distro }}-trilio-wlm:{{ triliovault_tag }}"
        command: 
          - /bin/bash
          - -c
          - /opt/create_cloud_trust.sh
        state: started
        detach: no
        interactive: yes
        network_mode: host
        tty: yes
        volumes:
          - /etc/kolla/triliovault-wlm-api/triliovault-wlm-api.conf:/etc/triliovault-wlm/triliovault-wlm.conf:ro
          - /etc/kolla/triliovault-wlm-api/api-paste.ini:/etc/triliovault-wlm/api-paste.ini:ro
          - /etc/kolla/triliovault-cloudrc:/opt/triliovault-cloudrc:rw
          - /etc/kolla/triliovault-wlm-api/create_cloud_trust.sh:/opt/create_cloud_trust.sh:rw
      tags: wlm_cloud_trust
