# permissions for end users to view tvocontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tvocontrolplane-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: tvo-operator
    app.kubernetes.io/part-of: tvo-operator
    app.kubernetes.io/managed-by: kustomize
  name: tvocontrolplane-viewer-role
rules:
- apiGroups:
  - demo.trilio.io
  resources:
  - tvocontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - demo.trilio.io
  resources:
  - tvocontrolplanes/status
  verbs:
  - get
