apiVersion: batch/v1
kind: Job
metadata:
  name: "job-triliovault-wlm-db-init"
  labels:
    application: triliovault
    component: wlm-db-init
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "-3"
spec:
  backoffLimit: 1000
  template:
    metadata:
      labels:
        application: triliovault
        component: wlm-db-init
    spec:
      securityContext:
        runAsUser: {{ .Values.common.nova_user_id }}
        fsGroup: {{ .Values.common.nova_group_id }}
      serviceAccountName: triliovault-wlm
      restartPolicy: OnFailure
      nodeSelector:
        triliovault-control-plane: enabled
      containers:
        - name: "wlm-db-init"
          securityContext:
            readOnlyRootFilesystem: false
            runAsUser: {{ .Values.common.nova_user_id }}
          image: {{ .Values.images.triliovault_wlm_api }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - -c
            - /tmp/triliovault-wlm-db-init.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: triliovault-wlm-bin
              mountPath: /tmp/triliovault-wlm-db-init.sh
              subPath: triliovault-wlm-db-init.sh
            - name: trilio-logs
              mountPath: /var/log/triliovault
            - mountPath: /etc/triliovault-wlm/wlm_logging.conf
              name: triliovault-wlm-etc
              readOnly: true
              subPath: wlm_logging.conf
            - name: triliovault-wlm-etc
              mountPath: /etc/triliovault-wlm/triliovault-wlm.conf
              subPath: triliovault-wlm.conf
              readOnly: true
            - name: triliovault-wlm-etc
              mountPath: /etc/triliovault-wlm/ca-cert.pem
              subPath: ca-cert.pem
              readOnly: true
            - name: triliovault-wlm-etc
              mountPath: /etc/triliovault-wlm/api-paste.ini
              subPath: api-paste.ini
              readOnly: true

      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: triliovault-wlm-bin
          configMap:
            name: "triliovault-wlm-bin"
            defaultMode: 0555
        - name: triliovault-wlm-etc
          secret:
            secretName: triliovault-wlm-etc
            defaultMode: 0444
        - name: trilio-logs
          emptyDir: {}
