# permissions for end users to edit tvocontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tvo-operator
    app.kubernetes.io/managed-by: kustomize
  name: tvocontrolplane-editor-role
rules:
- apiGroups:
  - tvo.trilio.io
  resources:
  - tvocontrolplanes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - tvo.trilio.io
  resources:
  - tvocontrolplanes/status
  verbs:
  - get
