# permissions for end users to view tvocontrolplanes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: tvo-operator
    app.kubernetes.io/managed-by: kustomize
  name: tvocontrolplane-viewer-role
rules:
- apiGroups:
  - tvo.trilio.io
  resources:
  - tvocontrolplanes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - tvo.trilio.io
  resources:
  - tvocontrolplanes/status
  verbs:
  - get
