heat_template_version: wallaby

description: >
  Trilio Datamover containerized service
parameters:
  ContainerTriliovaultDatamoverImage:
    default: ''
    description: The location of Trilio Datamover container image
    type: string
  ServiceData:
    default: {}
    description: Dictionary packing service data
    type: json
  ServiceNetMap:
    default: {}
    description: Mapping of service_name -> network name. Typically set
                 via parameter_defaults in the resource registry.  This
                 mapping overrides those in ServiceNetMapDefaults.
    type: json
  DefaultPasswords:
    default: {}
    type: json
  RoleName:
    default: ''
    description: Role name on which the service is applied
    type: string
  RoleParameters:
    default: {}
    description: Parameters specific to the role
    type: json
  EndpointMap:
    default: {}
    description: Mapping of service endpoint -> protocol. Typically set
                 via parameter_defaults in the resource registry.
    type: json
  CephClientUserName:
    default: openstack
    type: string
  CephClusterName:
    type: string
    default: ceph
    description: The Ceph cluster name.
    constraints:
    - allowed_pattern: "[a-zA-Z0-9]+"
      description: >
        The Ceph cluster name must be at least 1 character and contain only
        letters and numbers.
  CephConfigPath:
    type: string
    default: "/var/lib/tripleo-config/ceph"
    description: |
      The path where the Ceph Cluster config files are stored on the host.
  CinderEnableRbdBackend:
    default: false
    description: Whether ceph cinder backend enabled or not
    type: boolean	
  CephClientUserName: 
    default: 'openstack'	
    description: Cinder ceph backend user name
    type: string
  DatamoverApiDbUserPassword:
    description: The password for the trilio datamover db account
    type: string
    hidden: true
  EnableInternalTLS:
    type: boolean
    default: false
  MultipathdEnable:
    default: false
    description: Whether to enable the multipath daemon
    type: boolean
  NovaComputeOptVolumes:
    default: []
    description: list of optional vo
    type: comma_delimited_list
  TrilioDatamoverOptVolumes:
    default: []
    description: list of optional volumes to be mounted
    type: comma_delimited_list
  TrilioBackupTargets:
    default: []
    description: List of backup targets for TrilioVault
    type: json
  VmwareToOpenstackMigrationEnabled:
    default: false
    description: Whether to enable VMware to OpenStack migration feature or not
    type: boolean


conditions:

  internal_tls_enabled: {equals: [{get_param: EnableInternalTLS}, true]}

resources:

  ContainersCommon:
    type: /usr/share/openstack-tripleo-heat-templates/deployment/containers-common.yaml

outputs:
  role_data:
    description: Role data for the Trilio Datamover role.
    value:
      service_name: triliovault_datamover
      config_settings:
        trilio::contego::backup_targets: {get_param: TrilioBackupTargets}
        trilio::contego::cinder_backend_ceph: {get_param: CinderEnableRbdBackend}
        trilio::contego::ceph_cinder_user: {get_param: CephClientUserName}
        trilio::contego::vmware_to_openstack_migration_enabled: {get_param: VmwareToOpenstackMigrationEnabled}
        trilio::contego::database_connection:
          make_url:
            scheme: {get_param: [EndpointMap, MysqlInternal, protocol]}
            username: dmapi
            password: {get_param: DatamoverApiDbUserPassword}
            host: {get_param: [EndpointMap, MysqlInternal, host]}
            path: /dmapi
        trilio::contego::libvirt_images_rbd_ceph_conf:
          list_join:
          - ''
          - - '/etc/ceph/'
            - {get_param: CephClusterName}
            - '.conf'
      puppet_config:
        config_volume: triliovaultdm
        puppet_tags: dmconfig
        step_config: |
            include ::trilio::contego
        config_image: {get_param: ContainerTriliovaultDatamoverImage}
      kolla_config:
        /var/lib/kolla/config_files/triliovault_datamover.json:
          command: /opt/triliovault/start_triliovault_datamover.sh
          config_files:
            - source: "/var/lib/kolla/config_files/nova_libvirt/*"
              dest: "/"
              merge: true
              preserve_properties: true
            - source: "/var/lib/kolla/config_files/triliovaultdm/*"
              dest: "/"
              merge: true
              preserve_properties: true
            - source: "/var/lib/kolla/config_files/src-iscsid/*"
              dest: "/etc/iscsi/"
              merge: true
              preserve_properties: true
            - source: "/var/lib/kolla/config_files/src-ceph/"
              dest: "/etc/ceph/"
              merge: true
              preserve_properties: true
          permissions:
            - path: /var/log/triliovault
              owner: nova:nova
              recurse: true
            - path: /var/lib/nova/triliovault-mounts
              owner: nova:nova
              recurse: false
            - path:
                str_replace:
                  template: /etc/ceph/CLUSTER.client.USER.keyring
                  params:
                    CLUSTER: {get_param: CephClusterName}
                    USER: {get_param: CephClientUserName}
              owner: nova:nova
              perm: '0600'
      docker_config:
        step_5:
          triliovault_datamover:
            image: {get_param: ContainerTriliovaultDatamoverImage}
            net: host
            ipc: host
            privileged: true
            user: nova
            restart: always
            volumes:
              list_concat:
                - {get_attr: [ContainersCommon, volumes]}
                - {get_param: NovaComputeOptVolumes}
                - {get_param: TrilioDatamoverOptVolumes}
                -
                  - /var/lib/kolla/config_files/triliovault_datamover.json:/var/lib/kolla/config_files/config.json:ro
                  - /var/lib/config-data/puppet-generated/nova_libvirt/:/var/lib/kolla/config_files/nova_libvirt:ro
                  - /var/lib/config-data/puppet-generated/triliovaultdm/:/var/lib/kolla/config_files/triliovaultdm:ro
                  - /etc/iscsi:/var/lib/kolla/config_files/src-iscsid:ro
                  - list_join:
                    - ':'
                    - - {get_param: CephConfigPath}
                    - - '/var/lib/kolla/config_files/src-ceph'
                    - - 'ro'
                  - /dev:/dev
                  - /var/run/libvirt/:/var/run/libvirt/
                  - /var/log/containers/triliovault-datamover:/var/log/triliovault:z
                  - /var/lib/nova:/var/lib/nova:shared
                  - /etc/ssh/ssh_known_hosts:/etc/ssh/ssh_known_hosts:ro
                  - /lib/modules:/lib/modules:ro
                  - /run:/run
                  - /var/lib/iscsi:/var/lib/iscsi:z
                  - /var/lib/libvirt:/var/lib/libvirt:shared
                  - /sys/class/net:/sys/class/net
                  - /sys/bus/pci:/sys/bus/pci
                  - /boot:/boot:ro
                -
                  if:
                  - {equals: [{get_param: MultipathdEnable}, true]}
                  - - /etc/multipath:/etc/multipath:z
                    - /etc/multipath.conf:/etc/multipath.conf:ro
                  - []
            environment:
              KOLLA_CONFIG_STRATEGY: COPY_ALWAYS
      host_prep_tasks:
        - name: create trilio mounts directory
          file:
            path: "{{ item.path }}"
            state: directory
            setype: "{{ item.setype }}"
          with_items:
            - { 'path': /var/lib/nova/triliovault-mounts, 'setype': svirt_sandbox_file_t }
            - { 'path': /var/log/containers/triliovault-datamover, 'setype': svirt_sandbox_file_t }
      upgrade_tasks: []
