---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: operator-full-access-role
  namespace: triliovault
rules:
  # Grant access to all resources within the namespace
  - apiGroups: ["", "apps", "batch", "rbac.authorization.k8s.io", "route.openshift.io", "*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-full-access-rolebinding
  namespace: triliovault
subjects:
  - kind: ServiceAccount
    name: tvo-operator-controller-manager
    namespace: tvo-operator-system
roleRef:
  kind: Role
  name: operator-full-access-role
  apiGroup: rbac.authorization.k8s.io

