apiVersion: tvo.trilio.io/v1
kind: TVOControlPlane
metadata:
  name: tvocontrolplane-v60
spec:
  # Default values copied from <project_dir>/helm-charts/tvo-chart/values.yaml
  common:
    dmapi_workers: "16"
    memcached_servers: ""
    my_ip:
      host_interface: null
    nova_group_id: "42436"
    nova_user_id: "42436"
    oslo_enable_proxy_headers_parsing: false
    trustee_role: creator
  database:
    common:
      host: EDIT_DB_HOSTNAME
      root_password: EDIT_PASSWORD
      root_user_name: root
    datamover_api:
      database: dmapi
      password: EDIT_PASSWORD
      user: dmapi
    wlm_api:
      database: workloadmgr
      password: EDIT_PASSWORD
      user: workloadmgr
  helm3_hook: true
  images:
    bootstrap: docker.io/openstackhelm/heat:ocata-ubuntu_xenial
    db_drop: docker.io/openstackhelm/heat:ocata-ubuntu_xenial
    db_init: docker.io/openstackhelm/heat:ocata-ubuntu_xenial
    dep_check: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
    image_repo_sync: docker.io/docker:17.07.0
    ks_endpoints: docker.io/openstackhelm/heat:ocata-ubuntu_xenial
    ks_service: docker.io/openstackhelm/heat:ocata-ubuntu_xenial
    ks_user: docker.io/openstackhelm/heat:ocata-ubuntu_xenial
    local_registry:
      active: false
      exclude:
      - dep_check
      - image_repo_sync
    pull_policy: IfNotPresent
    rabbit_init: docker.io/rabbitmq:3.7-management
    triliovault_datamover_api: docker.io/trilio/trilio-datamover-api-helm:5.0.0-train-ubuntu_bionic
    triliovault_datamover_db_sync: docker.io/trilio/trilio-datamover-api-helm:5.0.0-train-ubuntu_bionic
    triliovault_object_store: docker.io/trilio/trilio-wlm-helm:5.0.0-train-ubuntu_bionic
    triliovault_wlm: docker.io/trilio/trilio-wlm-helm:5.0.0-train-ubuntu_bionic
    triliovault_wlm_api: docker.io/trilio/trilio-wlm-helm:5.0.0-train-ubuntu_bionic
    triliovault_wlm_cloud_trust: docker.io/trilio/trilio-wlm-helm:5.0.0-train-ubuntu_bionic
    triliovault_wlm_cron: docker.io/trilio/trilio-wlm-helm:5.0.0-train-ubuntu_bionic
    triliovault_wlm_db_sync: docker.io/trilio/trilio-wlm-helm:5.0.0-train-ubuntu_bionic
    triliovault_wlm_scheduler: docker.io/trilio/trilio-wlm-helm:5.0.0-train-ubuntu_bionic
    triliovault_wlm_workloads: docker.io/trilio/trilio-wlm-helm:5.0.0-train-ubuntu_bionic
  keystone:
    common:
      admin_role_name: admin
      auth_uri: ""
      auth_url: ""
      ca_cert: |
        CERT MULTIPLE LINES
      cloud_admin_domain_name: Default
      cloud_admin_project_id: ""
      cloud_admin_project_name: admin
      cloud_admin_user_name: admin
      cloud_admin_user_password: ""
      is_self_signed_ssl_cert: true
      keystone_auth_host: ""
      keystone_auth_port: ""
      keystone_auth_protocol: ""
      region_name: RegionOne
      service_project_domain_name: Default
      service_project_name: service
    datamover_api:
      admin_endpoint: ENDPOINT_PROTOCOL_ADMIN://ENDPOINT_HOST_ADMIN:8784/v2
      internal_endpoint: ENDPOINT_PROTOCOL_INTERNAL://ENDPOINT_HOST_INTERNAL:8784/v2
      password: EDIT_PASSWORD
      public_endpoint: ENDPOINT_PROTOCOL_PUBLIC://ENDPOINT_HOST_PUBLIC:8784/v2
      service_desc: TrilioVault Datamover Api Service
      service_name: dmapi
      servie_type: datamover
      user: dmapi
    identity: null
    keystone_interface: internal
    wlm_api:
      admin_endpoint: ENDPOINT_PROTOCOL_INTERNAL://ENDPOINT_HOST_ADMIN:8781/v1/$(tenant_id)s
      internal_endpoint: ENDPOINT_PROTOCOL_INTERNAL://ENDPOINT_HOST_INTERNAL:8781/v1/$(tenant_id)s
      password: EDIT_PASSWORD
      public_endpoint: ENDPOINT_PROTOCOL_PUBLIC://ENDPOINT_HOST_PUBLIC:8781/v1/$(tenant_id)s
      service_desc: TrilioVault Workloadmgr Api Service
      service_name: TrilioVaultWLM
      servie_type: workloads
      user: triliovault
  labels:
    datamover_api:
      node_selector_key: triliovault-control-plane
      node_selector_value: enabled
    wlm_api:
      node_selector_key: triliovault-control-plane
      node_selector_value: enabled
    wlm_cron:
      node_selector_key: triliovault-control-plane
      node_selector_value: enabled
    wlm_scheduler:
      node_selector_key: triliovault-control-plane
      node_selector_value: enabled
    wlm_workloads:
      node_selector_key: triliovault-control-plane
      node_selector_value: enabled
  pod:
    affinity:
      anti:
        topologyKey:
          default: kubernetes.io/hostname
        type:
          default: preferredDuringSchedulingIgnoredDuringExecution
        weight:
          default: 10
    lifecycle:
      disruption_budget:
        datamover_api:
          min_available: 2
        wlm_api:
          min_available: 2
      termination_grace_period:
        datamover:
          timeout: 30
        datamover_api:
          timeout: 30
        wlm_api:
          timeout: 30
        wlm_cron:
          timeout: 30
        wlm_scheduler:
          timeout: 30
        wlm_workloads:
          timeout: 30
      upgrades:
        daemonsets:
          datamover:
            enabled: true
            max_unavailable: 1
            min_ready_seconds: 0
          pod_replacement_strategy: RollingUpdate
        deployments:
          pod_replacement_strategy: RollingUpdate
          revision_history: 3
          rolling_update:
            max_surge: 3
            max_unavailable: 1
    mounts:
      triliovault_datamover:
        init_container: null
        triliovault_datamover:
          volumeMounts: null
          volumes: null
      triliovault_datamover_api:
        init_container: null
        triliovault_datamover_api:
          volumeMounts: null
          volumes: null
      triliovault_datamover_db_sync:
        triliovault_wlm_db_sync:
          volumeMounts: null
          volumes: null
      triliovault_tests:
        init_container: null
        triliovault_tests:
          volumeMounts: null
          volumes: null
      triliovault_wlm_api:
        init_container: null
        triliovault_wlm_api:
          volumeMounts: null
          volumes: null
      triliovault_wlm_cron:
        init_container: null
        triliovault_wlm_cron:
          volumeMounts: null
          volumes: null
      triliovault_wlm_db_sync:
        triliovault_wlm_db_sync:
          volumeMounts: null
          volumes: null
      triliovault_wlm_scheduler:
        init_container: null
        triliovault_wlm_scheduler:
          volumeMounts: null
          volumes: null
      triliovault_wlm_workloads:
        init_container: null
        triliovault_wlm_workloads:
          volumeMounts: null
          volumes: null
    replicas:
      triliovault_datamover_api: 3
      triliovault_wlm_api: 3
      triliovault_wlm_cron: 1
      triliovault_wlm_scheduler: 1
      triliovault_wlm_workloads: 3
    resources:
      datamover:
        limits:
          cpu: 2000m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 128Mi
      datamover_api:
        limits:
          cpu: 2000m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 128Mi
      enabled: false
      jobs:
        bootstrap:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        db_drop:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        db_init:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        db_sync:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        image_repo_sync:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ks_endpoints:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ks_service:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        ks_user:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        rabbit_init:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
        tests:
          limits:
            cpu: 2000m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
      wlm_api:
        limits:
          cpu: 2000m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 128Mi
      wlm_cron:
        limits:
          cpu: 2000m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 128Mi
      wlm_scheduler:
        limits:
          cpu: 2000m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 128Mi
      wlm_workloads:
        limits:
          cpu: 2000m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 128Mi
    security_context:
      triliovault:
        container:
          ceph_keyring_placement_triliovault:
            readOnlyRootFilesystem: false
            runAsGroup: 42424
            runAsUser: 42424
          triliovault_datamover:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 42424
          triliovault_datamover_api:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 63630
          triliovault_datamover_api_init:
            readOnlyRootFilesystem: false
            runAsGroup: 63630
            runAsUser: 0
          triliovault_datamover_init:
            readOnlyRootFilesystem: false
            runAsGroup: 42424
            runAsUser: 0
          triliovault_wlm_api:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 42424
          triliovault_wlm_cron:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 42424
          triliovault_wlm_init:
            readOnlyRootFilesystem: false
            runAsGroup: 42424
            runAsUser: 0
          triliovault_wlm_scheduler:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 42424
          triliovault_wlm_workloads:
            privileged: true
            readOnlyRootFilesystem: false
            runAsUser: 42424
          wlm_cloud_trust_creation:
            readOnlyRootFilesystem: false
            runAsGroup: 42424
            runAsUser: 42424
        pod:
          image_pull_secrets:
            default:
            - name: triliovault-image-pull-secret
          runAsUser: 42424
  rabbitmq:
    common:
      admin_password: EDIT_PASSWORD
      admin_user: admin
      host: EDIT_HOST
      notification_driver: messagingv2
      port: "5672"
    datamover_api:
      password: EDIT_PASSWORD
      user: dmapi
      vhost: dmapi
    wlm_api:
      password: EDIT_PASSWORD
      transport_url: ""
      user: workloadmgr
      vhost: workloadmgr
  triliovault_backup_targets:
  - backup_target_name: S3_BT1
    backup_target_type: s3
    is_default: true
    s3_access_key: ACCESSKEY1
    s3_auth_version: DEFAULT
    s3_bucket: BUCKET1
    s3_endpoint_url: ENDPOINT_URL1
    s3_region_name: REGION1
    s3_secret_key: SECRETKEY1
    s3_self_signed_cert: false
    s3_signature_version: default
    s3_ssl_enabled: true
    s3_ssl_verify: true
    s3_type: amazon_s3
  - backup_target_name: S3_BT2
    backup_target_type: s3
    is_default: true
    s3_access_key: ACCESSKEY2
    s3_auth_version: DEFAULT
    s3_bucket: BUCKET2
    s3_endpoint_url: ENDPOINT_URL2
    s3_region_name: REGION2
    s3_secret_key: SECRETKEY2
    s3_self_signed_cert: true
    s3_signature_version: default
    s3_ssl_ca_cert: |
      SSL_CERT_LINE_1
    s3_ssl_enabled: true
    s3_ssl_verify: true
    s3_type: amazon_s3
  - backup_target_name: NFS_BT3
    backup_target_type: nfs
    is_default: false
    nfs_options: nolock,soft,timeo=600,intr,lookupcache=none,nfsvers=3,retrans=10
    nfs_shares: 11.30.1.10:/mnt/share
  
  
