apiVersion: tvo.trilio.io/v1
kind: TVOControlPlane
metadata:
  name: tvocontrolplane-v61
spec:
  labels:
    wlm_api:
      node_selector_key: trilio-control-plane
      node_selector_value: enabled
    wlm_cron:
      node_selector_key: trilio-control-plane
      node_selector_value: enabled
    wlm_scheduler:
      node_selector_key: trilio-control-plane
      node_selector_value: enabled
    wlm_workloads:
      node_selector_key: trilio-control-plane
      node_selector_value: enabled
    datamover_api:
      node_selector_key: trilio-control-plane
      node_selector_value: enabled
  images:
    triliovault_wlm: docker.io/trilio/trilio-wlm:stable-6.0-rhoso18
    triliovault_wlm_api: docker.io/trilio/trilio-wlm:stable-6.0-rhosp18
    triliovault_wlm_scheduler: docker.io/trilio/trilio-wlm:stable-6.0-rhosp18
    triliovault_wlm_cron: docker.io/trilio/trilio-wlm:stable-6.0-rhosp18
    triliovault_wlm_workloads: docker.io/trilio/trilio-wlm:stable-6.0-rhosp18
    triliovault_wlm_cloud_trust: docker.io/trilio/trilio-wlm:stable-6.0-rhosp18
    triliovault_object_store: docker.io/trilio/trilio-wlm:stable-6.0-rhosp18
    triliovault_datamover_api: docker.io/trilio/trilio-datamover-api:stable-6.0-rhosp18
    triliovault_datamover_db_sync: docker.io/trilio/trilio-datamover-api:stable-6.0-rhosp18
    triliovault_wlm_db_sync: docker.io/trilio/trilio-wlm:stable-6.0-rhosp18
  common:
    nova_user_id: "42436"
    nova_group_id: "42436"
    trustee_role: "member"
    dmapi_workers: "16"
    memcached_servers: "memcached-0.memcached.openstack.svc:11212"
    oslo_enable_proxy_headers_parsing: false
  triliovault_backup_targets:
    - backup_target_name: 'BT1_S3'
      backup_target_type: 's3'
      is_default: False
      s3_type: 'amazon_s3'
      s3_access_key: ''
      s3_secret_key: ''
      s3_region_name: ''
      s3_bucket: ''
      s3_endpoint_url: ''
      s3_signature_version: 'default'
      s3_auth_version: 'DEFAULT'
      s3_ssl_enabled: true
      s3_ssl_verify: true
      s3_self_signed_cert: false
      s3_bucket_object_lock_enabled: false
    - backup_target_name: 'BT2_S3'
      backup_target_type: 's3'
      is_default: True
      s3_type: 'amazon_s3'
      s3_access_key: ''
      s3_secret_key: ''
      s3_region_name: ''
      s3_bucket: ''
      s3_endpoint_url: ''
      s3_signature_version: 'default'
      s3_auth_version: 'DEFAULT'
      s3_ssl_enabled: false
      s3_ssl_verify: false
      s3_self_signed_cert: false
      s3_bucket_object_lock_enabled: false
  keystone:
    keystone_interface: "internal"
    common:
      service_project_name: "service"
      service_project_domain_name: "Default"
      admin_role_name: "admin"
      cloud_admin_user_name: "admin"
      cloud_admin_user_password: "openstack"
      cloud_admin_project_name: "admin"
      cloud_admin_domain_name: "Default"
      region_name: "regionOne"
      auth_url: "https://keystone-internal.openstack.svc:5000"
      auth_uri: "https://keystone-internal.openstack.svc:5000/v3"
      keystone_auth_protocol: "https"
      keystone_auth_host: "keystone-internal.openstack.svc"
      keystone_auth_port: "5000"
      is_self_signed_ssl_cert: True
      ca_cert: |
        -----BEGIN CERTIFICATE-----
        fdwkldnnrmmgAwIBAgIRAIZiD8BmTf+GUM6FO0KM9ucwDQYJKoZIhvcNAQELBQAw
        GjEYMBYGA1UEAxMPcm9vdGNhLWludGVybmFsMB4XDTI0MTAyNTEwMjc1N1oXDTM0
        MTAyMzEwMjc1N1owGjEYMBYGA1UEAxMPcm9vdGNhLWludGVybmFsMIIBojANBgkq
        hkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAxufxDCr3CAxlRtjs/q6t98Vi1YwJI901
        /OJ5l21iKusTOTIPERdpku1PMq6keOuqFIV6vD4TlK5+DuopkULdBmtz2BXx97BA
        uTqoUVGkB1fQEJoZiHEsXB1kPLgXbo1XxtVDuV66FTNjePIsB7wQedtvJLGJltzJ
        RSd3hiIZOGeMEC2eEyzDiy+/DdeYR4mOjlQ0Q5GcWakzEXTO2nCGmZhx4vbpV6me
        VDkpEv3uCXk6vQngE2fqaQs66Jo3iM02hIY2YCJfgi4/dfcARXYIEzhBfc0G1AVL
        a5l9bH0N6H8SrS/0EDkJSNWwswnxHUQEA+WmS2uhncxKbUh5jtzZiHzrw6qkwMCZ
        DkWr5Q5rvs9QCsfHeLraQEMHv8MmWQQCle+ZrsFvmG+NWbSy74BAcr0vQfGu9GaE
        nml/WlmyeYKfwJ4X0TjAeSvI/53gz4iE87/vAOA0Y/uigCXPna6qdsnFs7HgQS+P
        J7qZtkdC5gxz+BYbq3AlFbBVij/Vnw01AgMBAAGjQjBAMA4GA1UdDwEB/wQEAwIC
        pDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTxcaYla3CvWoFLKS+1xCyTvhds
        8DANBgkqhkiG9w0BAQsFAAOCAYEAvHCg3QzlJnANgRD82RBh6yIMRxSgpcSHYuyS
        S8IE82R/cOf2GgP5HWZFOUaFZ+wG9T4y0j+97tt9jR3/0tVKVjWelpdLoVslEqHf
        n3IME9Ij/UhPclb7tPq4Fh3Xl2xNXRropb9A4aooT4gXUYkdexnXQMRP5vC/wKoB
        6Pa0xE0nqnoomXyLcOSE1RP0w9Gq1l6RlsiEIe3izCyiXZdyq+Z8VK1zoU/tGLvk
        mIN7uKsgVhdkx8GJb9CNxLAzsPiLrFics7VWObY7dhZ2bmJVMiyb22Ulr8Nsb2Pk
        GYQaP6laH5XcY1aj14bKq4WI9mbKuFEsoAhDR6kHElz0XPpAIFEztUVy1MRtritq
        6vWIkTm3JDnpwrFO+uwq3qD7fn0ldQ0uzQjvlLkiiWz8uqnNWVVlRoZyyijKMuYa
        YIBH9ZG0ZzXBC6dTIkuIuMiEVH0lvvgrqUhi3E4R8pTmZCjdCLzg+UgFoOAYvBA1
        QP7m1uoEN0eb5csgU2sjdkkel
        -----END CERTIFICATE-----
    datamover_api:
      user: "dmapi"
      password: "defajgh48zgt88wFzzhwEt3xHGeCOdExYbLGQN2XRm"
      service_name: "dmapi"
      service_type: "datamover"
      service_desc: "TrilioVault Datamover Api Service"
      internal_endpoint: "https://triliovault-datamover-internal.triliovault.svc:8784/v2"
      public_endpoint: "https://triliovault-datamover-public-triliovault.apps.trilio.trilio.bos2/v2"
      public_auth_host: "triliovault-datamover-public-triliovault.apps.trilio.trilio.bos2"
    wlm_api:
      user: "triliovault"
      password: "dsdeJl8axy0gv14fURwUUxy0qUOQbugUUOfXikz6j"
      service_name: "TrilioVaultWLM"
      service_type: "workloads"
      service_desc: "TrilioVault Workloadmgr Api Service"
      internal_endpoint: "https://triliovault-wlm-internal.triliovault.svc:8781/v1/$(tenant_id)s"
      public_endpoint: "https://triliovault-wlm-public-triliovault.apps.trilio.trilio.bos2/v1/$(tenant_id)s"
      public_auth_host: "triliovault-wlm-public-triliovault.apps.trilio.trilio.bos2"
  database:
    common:
      root_user_name: "root"
      root_password: "openstack"
      host: "openstack.openstack.svc"
      port: 3306
    datamover_api:
      user: "dmapi"
      password: "dsw21aSyH5gHH6XE72k11Y3t3C308jY5rP02ndwJW"
      database: "dmapi"
    wlm_api:
      user: "workloadmgr"
      password: "dfeeYb72OwUzX5YuRKcVjxXJaELV8YT0jZczIQwys0v"
      database: "workloadmgr"
  rabbitmq:
    common:
      admin_user: "admin"
      admin_password: "EDIT_PASSWORD"
      host: "EDIT_HOST"
      port: "15671"
      driver: "messagingv2"
      ssl: true
    datamover_api:
      user: "dmapi"
      password: "EDIT_PASSWORD"
      vhost: "dmapi"
      transport_url: "rabbit://dmapi:${PASSWORD}@${RABBITMQ_HOST}:5671/dmapi?ssl=1"
    wlm_api:
      user: "workloadmgr"
      password: "EDIT_PASSWORD"
      vhost: "workloadmgr"
      transport_url: "rabbit://workloadmgr:${PASSWORD}@${RABBITMQ_HOST}:5671/workloadmgr?ssl=1"
  helm3_hook: true
  pod:
    security_context:
      triliovault:
        container:
          triliovault_datamover_api:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            runAsUser: 63630
            runAsGroup: 0
          triliovault_wlm_api:
            readOnlyRootFilesystem: false
            privileged: true
            runAsUser: 42436
          triliovault_wlm_scheduler:
            readOnlyRootFilesystem: false
            privileged: true
            runAsUser: 42436
          triliovault_wlm_cron:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            runAsUser: 42436
          triliovault_wlm_workloads:
            readOnlyRootFilesystem: false
            privileged: true
            runAsUser: 42436
          triliovault_wlm_init:
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 42436
          triliovault_datamover_api_init:
            readOnlyRootFilesystem: false
            runAsUser: 0
            runAsGroup: 63630
          wlm_cloud_trust_creation:
            readOnlyRootFilesystem: false
            runAsUser: 42436
            runAsGroup: 42436
    replicas:
      triliovault_wlm_api: 3
      triliovault_datamover_api: 3
      triliovault_wlm_workloads: 3
      triliovault_wlm_cron: 1
      triliovault_wlm_scheduler: 3
      triliovault_object_store: 3

