---
- name: triliovault - set nbd module options in modprobe conf
  become: true
  template:
    src: modprobe-nbd.conf.j2
    dest: "/etc/modprobe.d/nbd.conf"

- name: triliovault - set module-load conf for nbd module
  become: true
  template:
    src: module-load-nbd.conf.j2
    dest: "/etc/modules-load.d/nbd.conf"

- name: triliovault - load nbd module
  become: true
  modprobe:
    name: "nbd"
    params: "nbds_max=128"
    state: "present"

- name: Ensuring config directories exist
  become: true
  file:
    path: "{{ node_config_directory }}/{{ item.key }}"
    state: "directory"
    owner: "{{ config_owner_user }}"
    group: "{{ config_owner_group }}"
    mode: "0770"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ triliovault_services }}"

- name: Ensuring /var/trilio directory exist
  become: true
  file:
    path: "{{ triliovault_parent_data_directory }}"
    state: "directory"
    owner: "{{ triliovault_datamover_user_id }}"
    group: "{{ triliovault_datamover_group_id }}"
    mode: "0755"

- name: Ensuring "{{ triliovault_parent_data_directory }}/triliovault-mounts"  directory exist
  become: true
  file:
    path: "{{ triliovault_parent_data_directory }}/triliovault-mounts"
    state: "directory"
    owner: "{{ triliovault_datamover_user_id }}"
    group: "{{ triliovault_datamover_group_id }}"
    mode: "0755"

#Copy certs now

- name: Copying triliovault datamover and datamover api conf files
  become: true
  template:
    src: "{{ item }}.conf.j2"
    dest: "{{ node_config_directory }}/{{ item }}/{{ item }}.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[item]
  with_items:
    - triliovault-datamover-api
    - triliovault-datamover
  notify:
    - "Restart {{ item }} container"

- name: Copying triliovault-datamover-object-store conf files
  become: true
  template:
    src: "triliovault-datamover-object-store.conf.j2"
    dest: "/etc/kolla/triliovault-datamover/triliovault-object-store.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_datamover_group]
  notify:
    - "Restart triliovault-datamover container"

- name: Copying fuse conf files
  become: true
  template:
    src: "fuse.conf.j2"
    dest: "{{ node_config_directory }}/{{ item.key }}/fuse.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[item.value.group]
    - item.value.enabled | bool
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart {{ item.key }} container"

- name: Copying triliovault-datamover-logging-conf files
  become: true
  template:
    src: "triliovault-datamover-logging.conf.j2"
    dest: "/etc/kolla/triliovault-datamover/triliovault-datamover-logging.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[triliovault_datamover_group]
  with_dict: "{{ triliovault_services }}"
  notify:
    - "Restart triliovault-datamover container"

- name: Copying triliovault-object-store-logging-conf files
  become: true
  template:
    src: "triliovault-object-store-logging.conf.j2"
    dest: "/etc/kolla/{{ item }}/triliovault-object-store-logging.conf"
    mode: "0660"
  when:
    - inventory_hostname in groups[item]
  with_items:
    - triliovault-datamover
    - triliovault-wlm-api
    - triliovault-wlm-cron
    - triliovault-wlm-scheduler
    - triliovault-wlm-workloads
  notify:
    - "Restart {{ item }} container"

- include_tasks: ceph_cinder.yml
  when:
    - cinder_backend_ceph | bool
    - inventory_hostname in groups[triliovault_datamover_group]

- include_tasks: ceph_nova.yml
  when:
    - nova_backend_ceph | bool
    - inventory_hostname in groups[triliovault_datamover_group]

- name: Copy over triliovault backup target certs - ceph s3 
  copy:
    src: "{{ node_custom_config }}/triliovault/{{ triliovault_s3_ssl_cert_file_name }}"
    dest: "{{ node_config_directory }}/{{ item }}/{{ triliovault_s3_ssl_cert_file_name }}"
    mode: "0660"
  become: true
  when:
    - triliovault_copy_ceph_s3_ssl_cert | bool
    - inventory_hostname in groups[item]
  with_items:
    - triliovault-datamover
    - triliovault-wlm-api
    - triliovault-wlm-cron
    - triliovault-wlm-scheduler
    - triliovault-wlm-workloads
  notify:
    - "Restart {{ item }} container"


- name: Copying over nova.conf for triliovault datamover service
  become: true
  vars:
    service_name: "triliovault-datamover"
  copy:
    src: "{{ node_config_directory }}/nova-compute/nova.conf"
    dest: "{{ node_config_directory }}/triliovault-datamover/nova.conf"
    mode: "0660"
    remote_src: yes
  when:
    - inventory_hostname in groups[triliovault_datamover_group]
    - enable_triliovault | bool
  notify:
    - "Restart triliovault-datamover container"


- name: Copy TrilioVault Service Start Scripts
  template:
    src: "start-{{ item }}.sh.j2"
    dest: "{{ node_config_directory }}/{{ item }}/start-{{ item }}.sh"
    mode: "0755"
  become: true
  when:
    - inventory_hostname in groups[item]
  with_items:
    - triliovault-datamover
    - triliovault-datamover-api
    - triliovault-wlm-api
    - triliovault-wlm-cron
    - triliovault-wlm-scheduler
    - triliovault-wlm-workloads
  notify:
    - "Restart {{ item }} container"

- include_tasks: check-containers.yml