---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triliovault-object-store
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-triliovault-object-store
subjects:
  - kind: ServiceAccount
    name: triliovault-object-store
    namespace: default