---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triliovault-object-store
  namespace: triliovault
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: default-triliovault-object-store
subjects:
  - kind: ServiceAccount
    name: triliovault-object-store
    namespace: triliovault
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: triliovault-object-store-anyuid
  namespace: triliovault
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:anyuid
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: triliovault-object-store
    namespace: triliovault